const CACHE = 'talkboard-v3';
const ASSETS = [
  './',
  './index.html',
  './manifest.webmanifest',
  './icon-180.png',
  './icon-512.png',
  './icons/arm.png',
  './icons/backpain.png',
  './icons/blanket.png',
  './icons/breathe.png',
  './icons/chest.png',
  './icons/closer.png',
  './icons/cold.png',
  './icons/confused.png',
  './icons/drink.png',
  './icons/drymouth.png',
  './icons/family.png',
  './icons/footy.png',
  './icons/forgive.png',
  './icons/frustrated.png',
  './icons/glasses.png',
  './icons/golf.png',
  './icons/goodbye.png',
  './icons/head.png',
  './icons/heart.png',
  './icons/holdhand.png',
  './icons/hot.png',
  './icons/hug.png',
  './icons/hungry.png',
  './icons/kiss.png',
  './icons/leg.png',
  './icons/love.png',
  './icons/medication.png',
  './icons/move.png',
  './icons/nurse.png',
  './icons/ok.png',
  './icons/pain.png',
  './icons/peace.png',
  './icons/proud.png',
  './icons/question.png',
  './icons/quiet.png',
  './icons/scared.png',
  './icons/sick.png',
  './icons/sit.png',
  './icons/sleep.png',
  './icons/sorry.png',
  './icons/stop.png',
  './icons/strong.png',
  './icons/talk.png',
  './icons/tennis.png',
  './icons/thanks.png',
  './icons/throat.png',
  './icons/together.png',
  './icons/toilet.png',
  './icons/tummy.png',
  './icons/tv.png',
  './icons/understand.png',
  './icons/wait.png',
  './icons/win.png',
  './icons/wrong.png',
  './audio/map.json',
  './audio/p000.mp3',
  './audio/p001.mp3',
  './audio/p002.mp3',
  './audio/p003.mp3',
  './audio/p004.mp3',
  './audio/p005.mp3',
  './audio/p006.mp3',
  './audio/p007.mp3',
  './audio/p008.mp3',
  './audio/p009.mp3',
  './audio/p010.mp3',
  './audio/p011.mp3',
  './audio/p012.mp3',
  './audio/p013.mp3',
  './audio/p014.mp3',
  './audio/p015.mp3',
  './audio/p016.mp3',
  './audio/p017.mp3',
  './audio/p018.mp3',
  './audio/p019.mp3',
  './audio/p020.mp3',
  './audio/p021.mp3',
  './audio/p022.mp3',
  './audio/p023.mp3',
  './audio/p024.mp3',
  './audio/p025.mp3',
  './audio/p026.mp3',
  './audio/p027.mp3',
  './audio/p028.mp3',
  './audio/p029.mp3',
  './audio/p030.mp3',
  './audio/p031.mp3',
  './audio/p032.mp3',
  './audio/p033.mp3',
  './audio/p034.mp3',
  './audio/p035.mp3',
  './audio/p036.mp3',
  './audio/p037.mp3',
  './audio/p038.mp3',
  './audio/p039.mp3',
  './audio/p040.mp3',
  './audio/p041.mp3',
  './audio/p042.mp3',
  './audio/p043.mp3',
  './audio/p044.mp3',
  './audio/p045.mp3',
  './audio/p046.mp3',
  './audio/p047.mp3',
  './audio/p048.mp3',
  './audio/p049.mp3',
  './audio/p050.mp3',
  './audio/p051.mp3',
  './audio/p052.mp3',
  './audio/p053.mp3',
  './audio/p054.mp3',
  './audio/p055.mp3',
  './audio/p056.mp3',
  './audio/p057.mp3',
  './audio/p058.mp3',
  './audio/p059.mp3',
  './audio/p060.mp3',
  './audio/p061.mp3',
  './audio/p062.mp3',
  './audio/p063.mp3',
  './audio/p064.mp3',
  './audio/p065.mp3',
  './audio/p066.mp3',
  './audio/p067.mp3',
  './audio/p068.mp3',
  './audio/p069.mp3',
  './audio/p070.mp3',
  './audio/p071.mp3',
  './audio/p072.mp3',
  './audio/p073.mp3',
  './audio/p074.mp3',
  './audio/p075.mp3',
  './audio/p076.mp3',
  './audio/p077.mp3',
  './audio/p078.mp3',
  './audio/p079.mp3',
  './audio/p080.mp3',
  './audio/p081.mp3',
  './audio/p082.mp3',
  './audio/p083.mp3',
  './audio/p084.mp3',
  './audio/p085.mp3',
  './audio/p086.mp3',
  './audio/p087.mp3',
  './audio/p088.mp3',
  './audio/p089.mp3',
  './audio/p090.mp3',
  './audio/p091.mp3',
  './audio/p092.mp3',
  './audio/p093.mp3',
  './audio/p094.mp3',
  './audio/p095.mp3',
  './audio/p096.mp3'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Network-first for navigation (so updates arrive), cache fallback for offline.
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    fetch(e.request)
      .then(res => {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
        return res;
      })
      .catch(() => caches.match(e.request, { ignoreSearch: true }).then(m => m || caches.match('./index.html')))
  );
});
