const CACHE = 'talkboard-v8';
// Precache the default voice (william); other voices are cached automatically when first used.
const ASSETS = [
  './',
  './index.html',
  './app.js',
  './manifest.webmanifest',
  './icon-180.png',
  './icon-512.png',
  './audio/map.json',
  './icons/air.png',
  './icons/alone.png',
  './icons/arm.png',
  './icons/backpain.png',
  './icons/blanket.png',
  './icons/breathe.png',
  './icons/bright.png',
  './icons/call.png',
  './icons/chest.png',
  './icons/closer.png',
  './icons/cold.png',
  './icons/confused.png',
  './icons/dizzy.png',
  './icons/drink.png',
  './icons/drymouth.png',
  './icons/eat.png',
  './icons/family.png',
  './icons/footy.png',
  './icons/forgive.png',
  './icons/frustrated.png',
  './icons/glasses.png',
  './icons/golf.png',
  './icons/goodbye.png',
  './icons/goodshot.png',
  './icons/head.png',
  './icons/heard.png',
  './icons/heart.png',
  './icons/help.png',
  './icons/holdhand.png',
  './icons/hot.png',
  './icons/hug.png',
  './icons/hungry.png',
  './icons/kiss.png',
  './icons/leg.png',
  './icons/loud.png',
  './icons/love.png',
  './icons/medication.png',
  './icons/move.png',
  './icons/music.png',
  './icons/neck.png',
  './icons/nurse.png',
  './icons/ok.png',
  './icons/pain.png',
  './icons/peace.png',
  './icons/phone.png',
  './icons/proud.png',
  './icons/question.png',
  './icons/quiet.png',
  './icons/scared.png',
  './icons/sick.png',
  './icons/sit.png',
  './icons/situp.png',
  './icons/sleep.png',
  './icons/sorry.png',
  './icons/stop.png',
  './icons/strong.png',
  './icons/talk.png',
  './icons/tea.png',
  './icons/tennis.png',
  './icons/thanks.png',
  './icons/throat.png',
  './icons/tissue.png',
  './icons/together.png',
  './icons/toilet.png',
  './icons/tummy.png',
  './icons/tv.png',
  './icons/understand.png',
  './icons/wait.png',
  './icons/water.png',
  './icons/win.png',
  './icons/wrong.png',
  './audio/william/p000.mp3',
  './audio/william/p001.mp3',
  './audio/william/p002.mp3',
  './audio/william/p003.mp3',
  './audio/william/p004.mp3',
  './audio/william/p005.mp3',
  './audio/william/p006.mp3',
  './audio/william/p007.mp3',
  './audio/william/p008.mp3',
  './audio/william/p009.mp3',
  './audio/william/p010.mp3',
  './audio/william/p011.mp3',
  './audio/william/p012.mp3',
  './audio/william/p013.mp3',
  './audio/william/p014.mp3',
  './audio/william/p015.mp3',
  './audio/william/p016.mp3',
  './audio/william/p017.mp3',
  './audio/william/p018.mp3',
  './audio/william/p019.mp3',
  './audio/william/p020.mp3',
  './audio/william/p021.mp3',
  './audio/william/p022.mp3',
  './audio/william/p023.mp3',
  './audio/william/p024.mp3',
  './audio/william/p025.mp3',
  './audio/william/p026.mp3',
  './audio/william/p027.mp3',
  './audio/william/p028.mp3',
  './audio/william/p029.mp3',
  './audio/william/p030.mp3',
  './audio/william/p031.mp3',
  './audio/william/p032.mp3',
  './audio/william/p033.mp3',
  './audio/william/p034.mp3',
  './audio/william/p035.mp3',
  './audio/william/p036.mp3',
  './audio/william/p037.mp3',
  './audio/william/p038.mp3',
  './audio/william/p039.mp3',
  './audio/william/p040.mp3',
  './audio/william/p041.mp3',
  './audio/william/p042.mp3',
  './audio/william/p043.mp3',
  './audio/william/p044.mp3',
  './audio/william/p045.mp3',
  './audio/william/p046.mp3',
  './audio/william/p047.mp3',
  './audio/william/p048.mp3',
  './audio/william/p049.mp3',
  './audio/william/p050.mp3',
  './audio/william/p051.mp3',
  './audio/william/p052.mp3',
  './audio/william/p053.mp3',
  './audio/william/p054.mp3',
  './audio/william/p055.mp3',
  './audio/william/p056.mp3',
  './audio/william/p057.mp3',
  './audio/william/p058.mp3',
  './audio/william/p059.mp3',
  './audio/william/p060.mp3',
  './audio/william/p061.mp3',
  './audio/william/p062.mp3',
  './audio/william/p063.mp3',
  './audio/william/p064.mp3',
  './audio/william/p065.mp3',
  './audio/william/p066.mp3',
  './audio/william/p067.mp3',
  './audio/william/p068.mp3',
  './audio/william/p069.mp3',
  './audio/william/p070.mp3',
  './audio/william/p071.mp3',
  './audio/william/p072.mp3',
  './audio/william/p073.mp3',
  './audio/william/p074.mp3',
  './audio/william/p075.mp3',
  './audio/william/p076.mp3',
  './audio/william/p077.mp3',
  './audio/william/p078.mp3',
  './audio/william/p079.mp3',
  './audio/william/p080.mp3',
  './audio/william/p081.mp3',
  './audio/william/p082.mp3',
  './audio/william/p083.mp3',
  './audio/william/p084.mp3',
  './audio/william/p085.mp3',
  './audio/william/p086.mp3',
  './audio/william/p087.mp3',
  './audio/william/p088.mp3',
  './audio/william/p089.mp3',
  './audio/william/p090.mp3',
  './audio/william/p091.mp3',
  './audio/william/p092.mp3',
  './audio/william/p093.mp3',
  './audio/william/p094.mp3',
  './audio/william/p095.mp3',
  './audio/william/p096.mp3',
  './audio/william/p097.mp3',
  './audio/william/p098.mp3',
  './audio/william/p099.mp3',
  './audio/william/p100.mp3',
  './audio/william/p101.mp3',
  './audio/william/p102.mp3',
  './audio/william/p103.mp3',
  './audio/william/p104.mp3',
  './audio/william/p105.mp3',
  './audio/william/p106.mp3',
  './audio/william/p107.mp3',
  './audio/william/p108.mp3',
  './audio/william/p109.mp3',
  './audio/william/p110.mp3',
  './audio/william/p111.mp3',
  './audio/william/p112.mp3',
  './audio/william/p113.mp3',
  './audio/william/p114.mp3',
  './audio/william/p115.mp3',
  './audio/william/p116.mp3',
  './audio/william/p117.mp3',
  './audio/william/p118.mp3',
  './audio/william/p119.mp3',
  './audio/william/p120.mp3',
  './audio/william/p121.mp3',
  './audio/william/p122.mp3',
  './audio/william/p123.mp3',
  './audio/william/p124.mp3',
  './audio/william/p125.mp3',
  './audio/william/p126.mp3',
  './audio/william/p127.mp3',
  './audio/william/p128.mp3',
  './audio/william/p129.mp3',
  './audio/william/p130.mp3',
  './audio/william/p131.mp3',
  './audio/william/p132.mp3',
  './audio/william/p133.mp3'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Network-first (so updates arrive), cache fallback for offline.
// App-shell files bypass the HTTP cache so a new deploy is picked up immediately;
// static assets (icons/audio) may revalidate normally.
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const shell = e.request.mode === 'navigate' ||
    /(?:index\.html|app\.js|map\.json|manifest\.webmanifest)$/.test(new URL(e.request.url).pathname);
  e.respondWith(
    fetch(e.request, shell ? { cache: 'no-cache' } : undefined)
      .then(res => {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
        return res;
      })
      .catch(() => caches.match(e.request, { ignoreSearch: true }).then(m => m || caches.match('./index.html')))
  );
});
